# Runs Bazel tests for DeepMind Lab

language: c++

dist: bionic

jdk:
  - oraclejdk8

addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
        key_url: 'https://bazel.build/bazel-release.pub.gpg'
    packages:
      - bazel
      - libffi-dev
      - gettext
      - freeglut3-dev
      - libsdl2-dev
      - libosmesa6-dev
      - python-dev
      - python-numpy
      - python-pil
      - python3-dev
      - python3-numpy
      - python3-pil

script:
  - bazel --bazelrc=.travis.bazelrc build --copt=-Wno-maybe-uninitialized --copt=-Wno-sign-compare //...
  - bazel --bazelrc=.travis.bazelrc test  --copt=-Wno-maybe-uninitialized --copt=-Wno-sign-compare //...
  - bazel --bazelrc=.travis.bazelrc run   --copt=-Wno-maybe-uninitialized --copt=-Wno-sign-compare --define headless=osmesa //:python_random_agent
